name: Setup Git environment
description: 🔶 Install and configure Git for GitHub Actions

branding:
  icon: settings
  color: orange

inputs:
  token:
    default: ${{ github.token }}
  git-version: {}
  user:
    default: github-actions[bot]
  user-name: {}
  user-email: {}

runs:
  using: node20
  main: dist/main.js
