name: Setup Git environment
description: 🔶 Install and configure Git for GitHub Actions

branding:
  icon: settings
  color: orange

inputs:
  github-token:
    default: ${{ github.token }}
  github-server-url:
    default: ${{ github.server_url }}
  # gitlab-token: {}
  # gitlab-server-url: {}
  # bitbucket-token: {}
  # bitbucket-server-url: {}
  user:
    default: github-actions[bot]
  user-name: {}
  user-email: {}
  safe-directory:
    default: .

runs:
  using: node20
  main: dist/main.js
